### ISSUE TITLE
action should be generic

### ISSUE THREAD

**Issue by j47996** [TurboTurtle/rig#12]
Rather than hardwiring a set of actions (sosreport, tcpdump, etc.) just give a
cmdline to run, as an arg to rig.  Then we can put whatever in a script.

**Comment by TurboTurtle** [comment]
I've played with the idea of having an 'exec' action, where a specific script could be executed, but we can't just pass in arbitrary commands as rig arguments. There are liability concerns with that.

Beyond that, users will want predictability and standardized ways of having actions run. If one rig captures data a certain way, they'll expect a second rig later on to capture it in the same manner every time - and that can't be guaranteed unless the mechanism for capturing the data remains consistent.

**Comment by TurboTurtle** [comment]
I've been mulling this over, and I'm not comfortable with adding an `exec` style action at this time. There's too many concerns around liability and stability in my mind. By binding responses to events to well-defined actions within the project, we not only ensure consistency of the data collected but the stability of doing so.

Further, for actions like `tcpdump`, it's be fairly complex to reliably provide that in the way suggested. The `tcpdump` action requires starting the tcpdump in a background process, monitoring that, and then gracefully terminating it after the rig is triggered. While that is straight forward to do with the `Action` class right now, dynamically providing that to arbitrary scripts is definitely not.
