### ISSUE TITLE
[rfe] Reoccurring log event actions

### ISSUE THREAD

**Issue by abhishekshah67** [TurboTurtle/rig#13]
log monitors can be clubbed with a counter and a delay to take the actions for a defined number of times with a minimum delay specified. 

This would extend the feature and would cover actions to be taken for a set of times and between some time intervals. 

Example:  # rig logs --reoccur 5 --delay=5 --message "This is my test message" --gcore my_failing_service

**Comment by TurboTurtle** [comment]
The `delay` function is one I've got on the back burner already, as something available to all rigs.

I like the idea of the counter, I'll see what I can cook up over the next few days.

**Comment by TurboTurtle** [comment]
@abhishekshah67 I've pushed a few commits to master that should address both of these.

Please try them out and let me know if I've missed anything you were asking for.

**Comment by abhishekshah67** [comment]
@TurboTurtle I'll try them out.

**Comment by TurboTurtle** [comment]
@abhishekshah67 just cycling around here - have you been able to test the changes? Obviously no rush, just wanted to touch base.

**Comment by abhishekshah67** [comment]
@TurboTurtle I tried to get rig to be working but seems I am missing something. 
` 
 File "/home/asah/workspace/rig/rig/rigging/rigs/logs.py", line 19, in <module>
    from systemd import journal
ModuleNotFoundError: No module named 'systemd'
`

460a9ec for count is a little different for what I wanted to convey. The current implementation of count would match the message for a number of times which is usefull as well. I was referring to a feature where thier would be a finite iteration of the triggered action when the condition is met. So this would mean number of triggered action and frequency of the action. 

Eg: Taking 5 thread dump in an interval of 5 seconds for a given condition.  Hope this clarifies.

**Comment by TurboTurtle** [comment]
For the first issue, you need `python3-systemd` installed. I'll update the README and spec file.

As for repeating actions... I can see the use case for `gcore`, but not really the other actions. I'll look into adding a `repeat` option.

**Comment by TurboTurtle** [comment]
@abhishekshah67 I've just pushed another change that adds the `--repeat` option that I believe addresses your request here.

PTAL and let me know if it covers your use case.

**Comment by TurboTurtle** [comment]
@abhishekshah67 follow up ping. Have you been able to test `--repeat` and `--repeat-delay` and does it fit your needs?

**Comment by abhishekshah67** [comment]
@TurboTurtle I tried some tests with system status --cpuperc and action noop(to avoid installtion of too many package in the container.)  The debug logs does not shows the action executed once. 
Not sure if I have hit a bug here. 

`[root@a136511c0013 rig]# python3 ./rig system --cpuperc 20 --noop --repeat 2 --repeat-delay 2 --debug
`

> 2019-10-29 05:47:27,007::aporp::DEBUG: Initializing system rig aporp
> 2019-10-29 05:47:27,011::aporp::DEBUG: Listening on /var/run/rig/aporp
> 2019-10-29 05:47:39,529::aporp::DEBUG: Received request 'status' from socket
> 2019-10-29 05:47:39,529::aporp::DEBUG: Sending '{'id': 'aporp', 'pid': '172', 'rig_type': 'system', 'watch': 'system utilization', 'trigger': 'CPU usage above 20.0%', 'status': 'Running'}' back to client
> 2019-10-29 05:48:14,195::aporp::DEBUG: Received request 'status' from socket
> 2019-10-29 05:48:14,195::aporp::DEBUG: Sending '{'id': 'aporp', 'pid': '172', 'rig_type': 'system', 'watch': 'system utilization', 'trigger': 'CPU usage above 20.0%', 'status': 'Running'}' back to client
> 2019-10-29 05:48:22,149::aporp::INFO: CPU usage at 34.6%, exceeding threshold of 20.0
> 2019-10-29 05:48:22,150::aporp::INFO: Watcher thread triggered. Stopping other watcher threads
> 2019-10-29 05:48:22,151::aporp::DEBUG: Triggering action noop
> 2019-10-29 05:48:22,151::aporp::INFO: No-op action triggered. Doing nothing.
> 2019-10-29 05:48:22,152::aporp::INFO: No data generated to archive for this rig.

ouplc: 

> 2019-10-29 05:59:02,706::ouplc::DEBUG: Initializing system rig ouplc
> 2019-10-29 05:59:02,710::ouplc::DEBUG: Listening on /var/run/rig/ouplc
> 2019-10-29 05:59:10,722::ouplc::INFO: CPU usage at 26.8%, exceeding threshold of 20.0
> 2019-10-29 05:59:10,723::ouplc::INFO: Watcher thread triggered. Stopping other watcher threads
> 2019-10-29 05:59:10,723::ouplc::DEBUG: Triggering action noop
> 2019-10-29 05:59:10,723::ouplc::INFO: No-op action triggered. Doing nothing.
> 2019-10-29 05:59:10,723::ouplc::INFO: No data generated to archive for this rig.

**Comment by TurboTurtle** [comment]
Yup, that's because `noop` is not repeatable. At the moment, only the `gcore` option is.

**Comment by abhishekshah67** [comment]
Tested. 
Gcore works fine. 

` python3 ./rig system --cpuperc 20 --gcore 134 --repeat 2 --repeat-delay 2 --debug`


> 019-10-31 04:35:48,389::onbde::DEBUG: Initializing system rig onbde
> 2019-10-31 04:35:48,391::onbde::DEBUG: Determined pid list to collect coredumps for to be: 134
> 2019-10-31 04:35:48,401::onbde::DEBUG: Listening on /var/run/rig/onbde
> 2019-10-31 04:35:53,412::onbde::INFO: CPU usage at 20.1%, exceeding threshold of 20.0
> 2019-10-31 04:35:53,412::onbde::INFO: Watcher thread triggered. Stopping other watcher threads
> 2019-10-31 04:35:53,412::onbde::DEBUG: Triggering action gcore
> 2019-10-31 04:35:53,412::onbde::DEBUG: Collecting gcore of 134 at /var/tmp/rig/onbde/core
> 2019-10-31 04:35:55,532::onbde::INFO: Triggering action gcore again. Repeat count is now 1. Will repeat 2 times total
> 2019-10-31 04:35:55,533::onbde::DEBUG: Collecting gcore of 134 at /var/tmp/rig/onbde/core-1
> 2019-10-31 04:35:57,626::onbde::INFO: Triggering action gcore again. Repeat count is now 2. Will repeat 2 times total
> 2019-10-31 04:35:57,628::onbde::DEBUG: Collecting gcore of 134 at /var/tmp/rig/onbde/core-2
> 2019-10-31 04:35:57,695::onbde::INFO: No data generated to archive for this rig.
>
