### ISSUE TITLE
[rfe] Provide distribution packaging for rig

### ISSUE THREAD

**Issue by bostrt** [TurboTurtle/rig#16]
It would be a friendlier user experience to have rig installable through pip instead of having to git-clone.

**Comment by bostrt** [comment]
Worth noting there is already a package called `rig` available via pip.

**Comment by TurboTurtle** [comment]
Keep in mind, rig is still in an alpha state at the moment. Once we get to a stable initial release I plan on packaging this for Fedora/EPEL, and if someone wants to volunteer to maintain is on some of the Debuntu's they are certainly welcome to, but I don't have any current plans to put rig in pip.

**Comment by bostrt** [comment]
Works for me! Distro packaging would be fantastic.

**Comment by TurboTurtle** [comment]
I've updated the title of this to be the generic tracker for distribution packaging.

**Comment by TurboTurtle** [comment]
rig is now shipping in F32+ in the official repos
