### ISSUE TITLE
[rig] --foreground doesn't work

### ISSUE THREAD

**Issue by mmatsuya** [TurboTurtle/rig#24]
--foreground option doesn't work. It's started in background even with the option.

```
# rig logs --foreground --logfile /var/log/messages -m "dumping master file: rename: example.com.zone: permission denied" --sosreport --gcore 15103 
jeygb
# 
```

**Comment by TurboTurtle** [comment]
Ack, easily reproduced. I think I see the issue, but will need to dig a little bit more to verify.

**Comment by TurboTurtle** [comment]
Yep, this is an easy fix. Thanks for the bug report, I'll get this sorted later today.
