### ISSUE TITLE
[rig] empty temporary directory was not deleted after rig destroy

### ISSUE THREAD

**Issue by mmatsuya** [TurboTurtle/rig#26]
The temporary directory was not deleted after rig destroy. It should be deleted by the destroy subcommand.
Otherwise, the unused empty directories will be created in it for each rig destroy command, 
and it's required to delete it manually.

```
# rig destroy -i jeygb
jeygb destroyed
# ls /var/tmp/rig
jeygb
# ls jeygb
# 
```

**Comment by TurboTurtle** [comment]
Ack. The check for removing the temp directory was too strict, in an effort to avoid accidental data deletion in case we failed to compress rig data for some reason.

Trivial fix, will be merged into master later today.
