### ISSUE TITLE
[RFE]:  tcpdump action of rig should have option to set snap length (-s)

### ISSUE THREAD

**Issue by prijeshpatel** [TurboTurtle/rig#33]
Currently, tcpdump action by rig capture the entire network frame(-s 0):

```
# ps -ef | grep tcpdump
root        1926       1  0 01:00 pts/0    00:00:00 /usr/sbin/tcpdump -Z root -s 0 -n -i ens3 -C 10 -W 1 -w /var/tmp/rig/mldrf/localhost.localdomain-22-11-2020-01:00:38-ens3.pcap
root        1936       1  0 01:00 ?        00:00:00 python3 rig logs -m tcpdump test --tcpdump --iface ens3
root        1993    1962  0 01:02 pts/1    00:00:00 grep --color=auto tcpdump
```

Usually we do not need entire frame to analyze most of the network issues, just frame header information is good enough. 

So, option to modify snap length can help in :
1. Reducing the capture size 
2. Tripping the data part of network frame(in case traffic is plain text) so that we can stop exposing data (from security perspective) when pcap is shared to some one for analyzation

Please see if it is possible to give a option to user to modify snap length (-s) for tcpdump

**Comment by TurboTurtle** [comment]
Ack. Should not be an issue to add this.
