### ISSUE TITLE
rig GA version ?

### ISSUE THREAD

**Issue by amtdas** [TurboTurtle/rig#38]
Would like to know 
   - when will GA available for rig?
   - Would it will be shipped as rpm in rhel ?

**Comment by TurboTurtle** [comment]
Rig is already in the Fedora repos, as version 1.0. There's not a set release cadence yet, but as usage grows I am envisioning a 6-month cadence.

RHEL testing is currently ongoing, and it is tentatively being discussed for a future minor release, depending on that testing.

**Comment by amtdas** [comment]
Will check Fedora repos. Thanks for the information.

**Comment by amtdas** [comment]
https://koji.fedoraproject.org/koji/packageinfo?packageID=31884
https://koji.fedoraproject.org/koji/buildinfo?buildID=1586448

**Comment by TurboTurtle** [comment]
Rig is now GA in RHEL 8.6 as version 1.0. rig-1.1 is in Fedora at this point.

**Comment by amtdas** [comment]
Great effort !!! Congrats !!! Thanks for the update.
